apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iotmyth-migration-backend
  name: iotmyth-migration-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotmyth-migration-backend
  template:
    metadata:
      labels:
        app: iotmyth-migration-backend
    spec:
      containers:
      - image: CONTAINER_IMAGE #ini didapatkan dari buildspec
        name: iotmyth-migration-backend
        imagePullPolicy: Always
        resources: 
          requests:
            memory: "10000Mi"
            cpu: "1000m"
        ports:
          - containerPort: 3000 
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: iotmyth-migration-backend
  namespace: default
  labels:
    run: iotmyth-migration-backend
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: iotmyth-migration-backend
  type: ClusterIP
