apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iotmyth-app
  name: iotmyth-app
  namespace: iotmyth
spec:
  replicas: 5
  selector:
    matchLabels:
      app: iotmyth-app
  template:
    metadata:
      labels:
        app: iotmyth-app
    spec:
      containers:
      - image: CONTAINER_IMAGE #ini didapatkan dari buildspec
        name: iotmyth-app
        imagePullPolicy: Always
        resources: 
          requests:
            memory: "3500Mi"
            cpu: "1000m"
        ports:
          - containerPort: 3080 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: iotmyth-app
  namespace: iotmyth
  labels:
    run: iotmyth-app
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3080
  selector:
    app: iotmyth-app
  type: NodePort
